### ISSUE TITLE
should this work on ubuntu?

### ISSUE THREAD

**Issue by phubaba** [nelsonenzo/tmux-appimage#10] opened 2020-08-06 04:07 UTC
Two issues.

1. My ubuntu didn't have yum by default. After I installed it ...
2. When I try to run the command
docker build . -t tmux                  

Sending build context to Docker daemon  204.3kB
Step 1/12 : FROM centos:centos6.9
 ---> 2199b8eb8390
Step 2/12 : RUN /usr/bin/yum -y update && /usr/bin/yum groupinstall -y "Development Tools" && yum clean all
 ---> Running in 3fc09637cccd
The command '/bin/sh -c /usr/bin/yum -y update && /usr/bin/yum groupinstall -y "Development Tools" && yum clean all' returned a non-zero code: 139

3. then I learned later that yum isn't used in ubuntu (apt-get is) so I removed it.

**Comment by nelsonenzo** [comment] 2021-01-31 03:31
You don't need yum installed locally, that's the whole purpose of Docker.
With that said, Centos 6 packages are a wreck right now and the error you are encountering is a duplicate of https://github.com/nelsonenzo/tmux-appimage/issues/11

I'm working on a fix for that issue and hope to have it resolved in the next day or so.

**Comment by nelsonenzo** [comment] 2021-01-31 19:20
I pushed the fix to the master branch.  Let me know if it doesn't work for you.

**Closed as completed** 2022-01-13 22:33 UTC
